<?php

namespace Database\Seeders\Demo;

use App\Enums\Booking\BookingStatus;
use App\Models\Booking\Booking;
use App\Models\Service\Service;
use App\Models\User\User;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Collection;

/**
 * Seeds demo bookings in various states.
 *
 * Important domain rule:
 * A professional cannot have overlapping bookings, even across different services.
 *
 * This seeder generates bookings per professional and distributes them across
 * that professional's active services without overlapping time ranges.
 */
class DemoBookingSeeder extends Seeder
{
    /**
     * Per-professional/day cursor to avoid overlapping demo bookings.
     *
     * @var array<string, Carbon>
     */
    private array $dayCursors = [];

    public function run(): void
    {
        $clients = User::query()
            ->where('role', 'client')
            ->orderBy('created_at')
            ->get();

        $services = Service::query()
            ->where('is_active', true)
            ->whereNotNull('professional_id')
            ->with('professional.user')
            ->orderBy('professional_id')
            ->orderBy('created_at')
            ->get();

        if ($clients->isEmpty() || $services->isEmpty()) {
            $this->command?->warn('⚠ No active services or clients found');
            return;
        }

        if (app()->environment('production')) {
            $this->command?->warn('⚠ DemoBookingSeeder skipped in production');
            return;
        }

        /*
         * Demo refresh:
         * Existing demo bookings generated by the old seeder may overlap.
         * Since this is a Demo seeder, we clean bookings for the demo clients/services
         * before creating a consistent timeline.
         */
        Booking::query()
            ->whereIn('service_id', $services->pluck('id'))
            ->whereIn('client_id', $clients->pluck('id'))
            ->delete();

        $bookingCount = 0;
        $clientIndex = 0;

        $servicesByProfessional = $services->groupBy('professional_id');

        foreach ($servicesByProfessional as $professionalId => $professionalServices) {
            $professionalServices = $professionalServices->values();

            if ($professionalServices->isEmpty()) {
                continue;
            }

            $serviceIndex = 0;

            /*
             * COMPLETED bookings - past dates
             */
            for ($i = 1; $i <= 5; $i++) {
                $service = $this->serviceFor($professionalServices, $serviceIndex++);
                $client = $this->clientFor($clients, $clientIndex++);

                $date = now()->subDays(20 - ($i * 3));
                $startsAt = $this->nextStartForProfessionalDay(
                    professionalId: $professionalId,
                    date: $date,
                    service: $service,
                );

                $this->createBooking($client, $service, $startsAt, BookingStatus::Completed, [
                    'completed_at' => $startsAt->copy()->addMinutes((int) $service->duration_minutes),
                    'confirmed_at' => $startsAt->copy()->subDays(2),
                    'paid_at' => $startsAt->copy()->subDay(),
                ]);

                $bookingCount++;
            }

            /*
             * PENDING bookings - future dates
             */
            for ($i = 1; $i <= 3; $i++) {
                $service = $this->serviceFor($professionalServices, $serviceIndex++);
                $client = $this->clientFor($clients, $clientIndex++);

                $date = now()->addDays(2 + ($i * 2));
                $startsAt = $this->nextStartForProfessionalDay(
                    professionalId: $professionalId,
                    date: $date,
                    service: $service,
                );

                $this->createBooking($client, $service, $startsAt, BookingStatus::Pending);

                $bookingCount++;
            }

            /*
             * CONFIRMED bookings - future dates
             */
            for ($i = 1; $i <= 3; $i++) {
                $service = $this->serviceFor($professionalServices, $serviceIndex++);
                $client = $this->clientFor($clients, $clientIndex++);

                $date = now()->addDay();
                $startsAt = $this->nextStartForProfessionalDay(
                    professionalId: $professionalId,
                    date: $date,
                    service: $service,
                );

                $this->createBooking($client, $service, $startsAt, BookingStatus::Confirmed, [
                    'confirmed_at' => now()->subDay(),
                ]);

                $bookingCount++;
            }

            /*
             * PAID bookings - future dates
             */
            for ($i = 1; $i <= 2; $i++) {
                $service = $this->serviceFor($professionalServices, $serviceIndex++);
                $client = $this->clientFor($clients, $clientIndex++);

                $date = now()->addDay();
                $startsAt = $this->nextStartForProfessionalDay(
                    professionalId: $professionalId,
                    date: $date,
                    service: $service,
                );

                $this->createBooking($client, $service, $startsAt, BookingStatus::Paid, [
                    'confirmed_at' => now()->subDays(2),
                    'paid_at' => now()->subDay(),
                ]);

                $bookingCount++;
            }

            /*
             * IN_PROGRESS booking - current booking.
             * One per professional.
             */
            $service = $this->serviceFor($professionalServices, $serviceIndex++);
            $client = $this->clientFor($clients, $clientIndex++);

            $minutesAgo = min(10, max(1, intdiv((int) $service->duration_minutes, 2)));
            $startsAt = now()->copy()->subMinutes($minutesAgo)->seconds(0);

            $this->createBooking($client, $service, $startsAt, BookingStatus::InProgress, [
                'confirmed_at' => now()->subDays(3),
                'paid_at' => now()->subDay(),
            ]);

            $bookingCount++;

            /*
             * CANCELLED bookings - one past, one future.
             * Cancelled bookings do not block agenda availability, but we still avoid
             * overlaps in demo data to keep the agenda visually clean.
             */
            for ($i = 1; $i <= 2; $i++) {
                $service = $this->serviceFor($professionalServices, $serviceIndex++);
                $client = $this->clientFor($clients, $clientIndex++);

                $date = $i === 1
                    ? now()->subDays(10)
                    : now()->addDays(7);

                $startsAt = $this->nextStartForProfessionalDay(
                    professionalId: $professionalId,
                    date: $date,
                    service: $service,
                );

                $this->createBooking($client, $service, $startsAt, BookingStatus::Cancelled, [
                    'cancelled_at' => $i === 1
                        ? $startsAt->copy()->addMinutes(15)
                        : now(),
                    'cancellation_reason' => $i === 1
                        ? 'Cliente canceló'
                        : 'Cambio de planes',
                ]);

                $bookingCount++;
            }

            /*
             * NO_SHOW booking - past date.
             */
            $service = $this->serviceFor($professionalServices, $serviceIndex++);
            $client = $this->clientFor($clients, $clientIndex++);

            $date = now()->subDays(3);
            $startsAt = $this->nextStartForProfessionalDay(
                professionalId: $professionalId,
                date: $date,
                service: $service,
            );

            $this->createBooking($client, $service, $startsAt, BookingStatus::NoShow, [
                'confirmed_at' => $startsAt->copy()->subDays(2),
                'paid_at' => $startsAt->copy()->subDay(),
            ]);

            $bookingCount++;
        }

        $this->command?->info("✓ Demo bookings created ({$bookingCount} total)");
    }

    private function serviceFor(Collection $services, int $index): Service
    {
        return $services[$index % $services->count()];
    }

    private function clientFor(Collection $clients, int $index): User
    {
        return $clients[$index % $clients->count()];
    }

    private function nextStartForProfessionalDay(
        string|int $professionalId,
        Carbon $date,
        Service $service,
    ): Carbon {
        $key = $professionalId.'|'.$date->toDateString();

        if (! isset($this->dayCursors[$key])) {
            $this->dayCursors[$key] = Carbon::parse($date->toDateString().' 09:00:00');
        }

        $startsAt = $this->dayCursors[$key]->copy();

        $duration = (int) $service->duration_minutes;
        $buffer = (int) $service->buffer_minutes;

        /*
         * Extra 15 minutes only for demo readability.
         * The real business buffer remains service->buffer_minutes.
         */
        $this->dayCursors[$key] = $startsAt
            ->copy()
            ->addMinutes($duration + $buffer + 15);

        return $startsAt;
    }

    private function createBooking(
        User $client,
        Service $service,
        Carbon $startsAt,
        BookingStatus $status,
        array $additionalData = []
    ): void {
        $endsAt = $startsAt->copy()->addMinutes((int) $service->duration_minutes);

        Booking::create(array_merge([
            'service_id' => $service->id,
            'professional_id' => $service->professional_id,
            'client_id' => $client->id,
            'starts_at' => $startsAt,
            'ends_at' => $endsAt,
            'status' => $status,
            'modality' => $service->modality,
            'price_snapshot' => $service->price,
            'duration_minutes_snapshot' => $service->duration_minutes,
            'confirmed_at' => null,
            'paid_at' => null,
            'cancelled_at' => null,
            'cancellation_reason' => null,
            'reschedule_reason' => null,
        ], $additionalData));
    }
}
