port: 7880

bind_addresses:
  - ""

rtc:
  tcp_port: 7881
  port_range_start: 60000
  port_range_end: 60100
  use_external_ip: true

keys:
  proconnect_prod_key: r9ZP6uROa1pWeqABtt9xTtoXtBMgZoG2HoTauMr9Om23aW6cTOupP3wf2XoFlfOr
